[package]
name = "nextclade"
version = "3.1.0"
description = "Alignment, mutation calling, phylogenetic placement, clade assignment and quality control checks for viral genetic sequences. Library module."
repository = "https://github.com/nextstrain/nextclade"
documentation = "https://docs.nextstrain.org/projects/nextclade/en/stable/"
homepage = "https://clades.nextstrain.org/"
edition = "2021"
license = "MIT"
publish = false

[lib]
crate-type = ["lib"]

[dependencies]
assert2 = "=0.3.11"
auto_ops = "=0.3.0"
bio = "=1.5.0"
bio-types = "=1.0.1"
chrono = { version = "=0.4.33", default-features = false, features = ["clock", "std", "wasmbind"] }
clap = { version = "=4.5.0", features = ["derive", "color", "unicode", "unstable-styles"] }
clap_complete = "=4.5.0"
clap_complete_fig = "=4.5.0"
color-eyre = "=0.6.2"
csv = "=1.3.0"
ctor = "=0.2.6"
derive_more = "=0.99.17"
edit-distance = "=2.1.0"
either = "=1.9.0"
env_logger = "=0.11.1"
eyre = "=0.6.12"
flate2 = "=1.0.28"
gcollections = "=1.5.0"
getrandom = "=0.2.12"
indexmap = { version = "=2.2.2", features = ["serde"] }
intervallum = "=1.4.1"
itertools = "=0.12.1"
lazy_static = "=1.4.0"
log = "=0.4.20"
maplit = "=1.0.2"
multimap = "=0.9.1"
num = "=0.4.1"
num-traits = "=0.2.18"
num_cpus = "=1.16.0"
optfield = "=0.3.0"
ordered-float = { version = "=4.2.0", features = ["rand", "serde", "schemars"] }
owo-colors = "=4.0.0"
pretty_assertions = "=1.4.0"
rayon = "=1.8.1"
regex = "=1.10.3"
schemars = { version = "=0.8.16", features = ["chrono", "either", "enumset", "indexmap2"] }
semver = { version = "=1.0.21", features = ["serde"] }
serde = { version = "=1.0.196", features = ["derive"] }
serde_json = { version = "=1.0.113", features = ["preserve_order", "indexmap", "unbounded_depth"] }
serde_repr = "=0.1.18"
serde_stacker = { version = "=0.1.11" }
serde_yaml = "=0.9.31"
strsim = "=0.11.0"
strum = "=0.26.1"
strum_macros = "=0.26.1"
tinytemplate = "=1.2.1"
traversal = "=0.1.2"
urlencoding = "=2.1.3"
validator = { version = "=0.16.1", features = ["derive"] }
wasm-bindgen = { version = "=0.2.91", features = ["serde-serialize"] }
zip = { version = "=0.6.6", default-features = false, features = ["aes-crypto", "deflate", "time"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
atty = "=0.2.14"
bzip2 = { version = "=0.4.4", features = ["static"] }
xz2 = { version = "=0.1.7", features = ["static"] }
zstd = { version = "=0.13.0", features = ["zstdmt"] }

[dev-dependencies]
assert2 = "=0.3.11"
criterion = { version = "=0.5.1", features = ["html_reports"] }
rstest = "=0.18.2"
rstest_reuse = "=0.6.0"


[[bench]]
name = "bench_create_stripes"
harness = false

[[bench]]
name = "bench_seed_alignment"
harness = false
