[package]
name = "nextclade-cli"
version = "3.1.0"
description = "Alignment, mutation calling, phylogenetic placement, clade assignment and quality control checks for viral genetic sequences. CLI module."
repository = "https://github.com/nextstrain/nextclade"
documentation = "https://docs.nextstrain.org/projects/nextclade/en/stable/"
homepage = "https://clades.nextstrain.org/"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
assert2 = "=0.3.11"
clap = { version = "=4.5.0", features = ["derive", "color", "unicode", "unstable-styles"] }
clap-markdown = "=0.1.3"
clap_complete = "=4.5.0"
clap_complete_fig = "=4.5.0"
color-eyre = "=0.6.2"
comfy-table = "=7.1.0"
crossbeam = "=0.8.4"
crossbeam-channel = "=0.5.11"
ctor = "=0.2.6"
dotenv = "=0.15.0"
dotenv_codegen = "=0.15.0"
eyre = "=0.6.12"
indexmap = { version = "=2.2.2", features = ["serde"] }
itertools = "=0.12.1"
lazy_static = "=1.4.0"
log = "=0.4.20"
nextclade = { path = "../nextclade" }
num_cpus = "=1.16.0"
ordered-float = { version = "=4.2.0", features = ["rand", "serde", "schemars"] }
owo-colors = "=4.0.0"
pretty_assertions = "=1.4.0"
rayon = "=1.8.1"
regex = "=1.10.3"
reqwest = { version = "=0.11.24", default-features = false, features = ["blocking", "deflate", "gzip", "brotli", "socks", "rustls-tls"] }
schemars = { version = "=0.8.16", features = ["chrono", "either", "enumset", "indexmap1"] }
semver = { version = "=1.0.21", features = ["serde"] }
serde = { version = "=1.0.196", features = ["derive"] }
serde_json = { version = "=1.0.113", features = ["preserve_order", "indexmap", "unbounded_depth"] }
strum = "=0.26.1"
strum_macros = "=0.26"
tinytemplate = "=1.2.1"
url = { version = "=2.5.0", features = ["serde"] }
zip = { version = "=0.6.6", default-features = false, features = ["aes-crypto", "bzip2", "deflate", "time"] }

[dev-dependencies]
assert2 = "=0.3.11"
criterion = { version = "=0.5.1", features = ["html_reports"] }
rstest = "=0.18.2"
rstest_reuse = "=0.6.0"
