[package]
name = "nextclade-web"
version = "3.1.0"
description = "Alignment, mutation calling, phylogenetic placement, clade assignment and quality control checks for viral genetic sequences. WebAssembly module."
edition = "2021"
license = "MIT"
publish = false
build = "src/build.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
assert2 = "=0.3.11"
chrono = { version = "=0.4.33", default-features = false, features = ["clock", "std", "wasmbind"] }
console_error_panic_hook = "=0.1.7"
eyre = "=0.6.12"
getrandom = { version = "=0.2.12", features = ["js"] }
itertools = "=0.12.1"
js-sys = { version = "=0.3.68", features = [] }
log = "=0.4.20"
nextclade = { path = "../nextclade" }
schemars = { version = "=0.8.16", features = ["chrono", "either", "enumset", "indexmap1"] }
serde = { version = "=1.0.196", features = ["derive"] }
serde-wasm-bindgen = { version = "=0.6.3" }
wasm-bindgen = { version = "=0.2.91", features = ["serde-serialize"] }
wasm-logger = "=0.2.0"
web-sys = { version = "=0.3.68", features = ["console"] }

[build-dependencies]
nextclade = { path = "../nextclade" }
schemars = { version = "=0.8.16", features = ["chrono", "either", "enumset", "indexmap1"] }
eyre = "=0.6.12"

[dev-dependencies]
assert2 = "=0.3.11"
wasm-bindgen-test = "=0.3.41"
